# Generated by Django 4.1.2 on 2022-10-16 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.TextField(blank=True, null=True, verbose_name='buyer')),
                ('provider', models.TextField(blank=True, null=True, verbose_name='provider')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('status', models.CharField(choices=[('R', 'Solicitado'), ('C', 'Confirmado'), ('PS', 'Pago Enviado'), ('PR', 'Pago Rechazado'), ('P', 'Pagado'), ('I', 'En Proceso'), ('F', 'Finalizado'), ('CA', 'Cancelada')], default='R', max_length=2, verbose_name='status')),
                ('duration', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(limit_value=30), django.core.validators.MaxValueValidator(limit_value=240)], verbose_name='duration (minutes)')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
            },
        ),
    ]
